trigger:
  - main
 
pool:
  # vmImage: 'ubuntu-latest'*
  name: self-hosted-agent-pool

stages:
- stage: FetchKeyVaultSecrets
  displayName: 'Fetch Secrets from the vault'
  jobs:
  - job: FetchKeyVaultSecrets
    displayName: 'Fetch URLs from Azure Key Vault'
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'v2devop-wif'
        KeyVaultName: 'v2devops-new-test'
        # SecretsFilter: '*'
        RunAsPreJob: false
    - script: |
        echo "Container1 URL: $(test)"
      displayName: 'Display fetched URLs'

  # - job: UpdateContainerApps
  #   displayName: 'Update Azure Container Apps Environment Variables'
  #   dependsOn: FetchKeyVaultSecrets
  #   pool:
  #     vmImage: 'ubuntu-latest'
  #   steps:
  #   - script: |
  #       az webapp config appsettings set --name '<YourContainerApp1Name>' --resource-group '<YourResourceGroup>' --settings 'CONTAINER2_URL=$(Container2Url)'
  #       az webapp config appsettings set --name '<YourContainerApp2Name>' --resource-group '<YourResourceGroup>' --settings 'CONTAINER1_URL=$(Container1Url)'
  #     displayName: 'Update Azure Container Apps'