trigger:
  - main
 
pool:
  # vmImage: 'ubuntu-latest'*
  name: self-hosted-agent-pool

stages:
- stage: FetchKeyVaultSecrets
  displayName: 'Fetch Secrets from the vault'
  jobs:
  - job: FetchKeyVaultSecrets
    displayName: 'Fetch URLs from Azure Key Vault'
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'v2devop-wif'
        KeyVaultName: 'v2devops-new-test'
        # SecretsFilter: '*'
        RunAsPreJob: false
    - script: |
        echo "Container1 URL: $(Container1Url)" >> output.txt
        echo "Container2 URL: $(Container2Url)" >> output.txt
        cat output.txt
      displayName: 'Display fetched URLs'

  - job: UpdateContainerApps
    displayName: 'Update Azure Container Apps Environment Variables'
    dependsOn: FetchKeyVaultSecrets
    # pool:
    #   vmImage: 'ubuntu-latest'
    steps:
    - script: |
        az containerapp update -n callmindtestcontainer -g v2devops-new --set-env-vars CONTAINER2_URL=$(Container2Url)
      displayName: 'Update Azure Container Apps'

  # - job: Push
  #   displayName: 'Build, Push & Deploy'
  #   steps:
  #   - task: AzureContainerApps@1
  #     inputs:
  #       # appSourcePath: '$(Build.SourcesDirectory)'
  #       azureSubscription: 'v2devop-wif'
  #       # acrName: 'callminduatconregistry'
  #       # imageToDeploy: 'callmindacrdev.azurecr.io/callmindui:$(Build.BuildId)'
  #       imageToBuild : callminduatconregistry.azurecr.io/callmindvoice:$(Build.BuildId)
  #       containerAppName: 'callmindvoice'
  #       resourceGroup: 'callmindrguat'
  #       # environmentVariables: |
  #       #   AZURE_REGION=$(AZURE_REGION_DEV)
  #       #   AZURE_SPEECH_KEY=$(AZURE_SPEECH_KEY_DEV)
  #       #   APP_SVC_CONNECTION=$(APP_SVC_CONNECTION_DEV)
  #       #   AI_SVC_CONNECTION=$(AI_SVC_CONNECTION_DEV)
  #       #   SPEECH_SVC_CONNECTION=$(SPEECH_SVC_CONNECTION_DEV)
  #       #   LANG_PRECISON_NUM=$(LANG_PRECISON_NUM_DEV)    