trigger:
  branches:
    include:
      - dev
 
pool:
  name: self-hosted-agent-pool

stages:
- template: '..\..\templates\deploy-infra.yaml'
  parameters:
    branchName: variables['Build.SourceBranchName']
    environment: 'dev'
    location: 'eastus'
    azureServiceConnection: 'azuredevopssp'