trigger:
  branches:
    include:
      - "*"
      # - qa
      # - uat
      # - main
 
pool:
  # vmImage: 'ubuntu-latest'$
  name: self-hosted-agent-pool

stages:
- template: templates\deploy-infra.yaml
  parameters:
    branchName: 'dev'

- template: templates\deploy-infra.yaml
  parameters:
    branchName: 'qa'

- template: templates\deploy-infra.yaml
  parameters:
    branchName: 'uat'
# stages:
# - stage: deploy_infra
#   displayName: 'Deploy Infrastructure'
#   # condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
#   jobs:
#   - job: deploy_dev
#     displayName: 'Deploy to Dev'
#     steps:
#     - template: templates\terraform-setup.yaml
#       parameters:
#         terraformVersion: 'latest'
    
#     - template: templates\statefile-storage.yaml
#       parameters:
#         azureServiceConnection: ''
#         resourceGroupName: 'callmindsfrg'
#         location: 'eastus'
#         storageAccountName: 'statecsdev'
#         containerName: variables['Build.SourceBranch']

#     - template: templates\terragrunt-apply.yaml
#       parameters:
#         environment: variables['Build.SourceBranch']

# - stage: deploy_qa
#   displayName: 'Deploy to QA'
#   condition: eq(variables['Build.SourceBranch'], 'refs/heads/qa')
#   jobs:
#   - job: deploy_qa
#     displayName: 'Deploy to QA'
#     steps:
#     - template: templates\terraform-setup.yaml
#       parameters:
#         terraformVersion: 'latest'
    
#     - template: templates\statefile-storage.yaml
#       parameters:
#         resourceGroupName: 'rg-terragrunt-backend-state-qa'
#         location: 'eastus'
#         storageAccountName: 'callmindterraformstate-qa'
#         containerName: 'qa'

    # - template: templates\terragrunt-apply.yaml
    #   parameters:
    #     environment: 'qa'

# - stage: deploy_staging
#   displayName: 'Deploy to Staging'
#   jobs:
#   - job: deploy_staging
#     displayName: 'Deploy to Staging'
#     steps:
#     - template: templates\terraform-setup.yaml
#       parameters:
#         terraformVersion: 'latest'
    
#     - template: templates\statefile-storage.yaml
#       parameters:
#         resourceGroupName: 'rg-terragrunt-backend-state-staging'
#         location: 'eastus'
#         storageAccountName: 'callmindterraformstate-staging'
#         containerName: 'staging'

#     - template: templates\terragrunt-apply.yaml
#       parameters:
#         environment: 'staging'