trigger:
  - main
  - sagar-*
 
pool:
  # vmImage: 'ubuntu-latest'
  name: self-hosted-agent-pool

stages:
- stage: deploy-dev
  displayName: 'Deploy to Dev'
  jobs:
  - job: deploy_dev
    displayName: 'Deploy to Dev'
    steps:
    - template: templates\terraform-setup.yml
      parameters:
        terraformVersion: 'latest'
    
    - template: templates\statefile-storage.yml
      parameters:
        resourceGroupName: 'rg-terragrunt-backend-state-dev'
        location: 'eastus'
        storageAccountName: 'callmindterraformstate-dev'
        containerName: 'dev'

    - template: templates\terragrunt-apply.yml
      parameters:
        environment: 'dev'

# - stage: deploy-qa
#   displayName: 'Deploy to QA'
#   jobs:
#   - job: deploy_qa
#     displayName: 'Deploy to QA'
#     steps:
#     - template: templates\terraform-setup.yml
#       parameters:
#         terraformVersion: 'latest'
    
#     - template: templates\statefile-storage.yml
#       parameters:
#         resourceGroupName: 'rg-terragrunt-backend-state-qa'
#         location: 'eastus'
#         storageAccountName: 'callmindterraformstate-qa'
#         containerName: 'qa'

#     - template: templates\terragrunt-apply.yml
#       parameters:
#         environment: 'qa'

# - stage: deploy-staging
#   displayName: 'Deploy to Staging'
#   jobs:
#   - job: deploy_staging
#     displayName: 'Deploy to Staging'
#     steps:
#     - template: templates\terraform-setup.yml
#       parameters:
#         terraformVersion: 'latest'
    
#     - template: templates\statefile-storage.yml
#       parameters:
#         resourceGroupName: 'rg-terragrunt-backend-state-staging'
#         location: 'eastus'
#         storageAccountName: 'callmindterraformstate-staging'
#         containerName: 'staging'

#     - template: templates\terragrunt-apply.yml
#       parameters:
#         environment: 'staging'