name: Multi Event Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:  
  multi-event:
    runs-on: ubuntu-latest
    steps:
      - name: "Multi Event Demo"
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job id: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"