#This is a multi event workflow demo
name: 'MultiEvent Demo'
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  release:
    type: [published, created]

jobs:
  multi-event:
    runs-on: ubuntu-latest
    steps:
      - name: "Multi Event Demo"
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job id: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"