parameters:
  environment: ''

steps:
  - task: AzureCLI@2
    displayName: Terragrunt apply
    inputs:
      azureSubscription: 'v2devops-service-connection'
      scriptType: 'bash'
      addSpnToEnvironment: true
      scriptLocation: 'inlineScript'
      inlineScript: |
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_TENANT_ID=$tenantId
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        
        cd $(Pipeline.Workspace)/environment/${{ parameters.environment }}
        terragrunt run-all apply --terragrunt-non-interactive
